### ISSUE TITLE
Exception in thread "PortalConnector"

### ISSUE THREAD

**Issue by rucksman** [Tommy-LSA/supoxy#3]
When starting supoxy I get the following error:

$  java -Djava.library.path=./SuPoxy_lib -jar SuPoxy.jar sunny.conf &
[1] 1750
$ 01/27/2017 17:20:26 Use default value for timecorrection (0)
01/27/2017 17:20:27     API Thread started
01/27/2017 17:20:27     SuPoxy is running at  8000
01/27/2017 17:20:28     SuPoxy try to log in
01/27/2017 17:20:30     login done
01/27/2017 17:20:30     SuPoxy login done
Exception in thread "PortalConnector" java.lang.NumberFormatException: For input string: "pe":"DateTime"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at de.waldmensch.SuPoxyDataObject.<init>(SuPoxyDataObject.java:21)
        at de.waldmensch.SuPoxyConnect.getLiveData(SuPoxyConnect.java:144)
        at de.waldmensch.SuPoxyConnect.WebConnect(SuPoxyConnect.java:119)
        at de.waldmensch.SuPoxyConnect.run(SuPoxyConnect.java:76)

I am running Ubuntu 16.04 and OpenJDK 8.

**Comment by Gerrit-KMeier** [comment]
+1 I'm having the same issue
